#! /usr/bin/env bash

clear
read -p "Enter Date on which you want how many users were logged in (E.g. 5): " date
read -p "Enter Month on which you want how many users were logged in (E.g. Aug): " month
read -p "Enter Year on which you want how many users were logged in (E.g. 2019): " year


isSingleDigit=`echo $date | wc -m`

if [ $isSingleDigit  -eq 2 ]
then
	last -F | awk -F ' - ' '{print $1}' | grep "$month.*  $date.* $year"
else
	last -F | awk -F ' - ' '{print $1}' | grep "$month.*$date.*$year" 
fi

#last | grep -i "$day"
